language: node_js
node_js:
  - 0.10
  - 4
  - 6
  - 7
  - 8
  - 9
  - 11
  - 12
  - 13
  - 13
  - 14
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: focal
    # local imports fetch the same git commit ref
      import:
      - .travis-buster.yml
      #.travis-stretch.yml

script:
  - npm run lint
  - npm run test
  - npm run test-coverage && cat coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf coverage

# local imports fetch the same git commit ref
#import:
#- one.yml
#- path/to/other.yml
